spring:
  application:
    name: notification-multichannel

  datasource:
    url: jdbc:mysql://localhost:3307/notification_multichannel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: notification_user
    password: notification_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          max-interval: 10000ms
          multiplier: 2

server:
  port: 8080
